sudo: required
language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  api_key:
    secure: "H3gMPSWbMBJ8rqow3/hI6wyPXB5GzBfmw5qmS1KGwEHjBcDZrfs8gFNHGSnkN4ykJXbKi+JLCRsAK8r+ZVXyVVFoY6zyM8Ltl/TpdG3zVBoJx0bBrugYyN3wD/T6nF15GulJW3CY3ly8BV/0eWWQrZ5CUKjS2ofQhiHgbwze4cVPD4M4hXY6hIECx86KTAbUMZz1v8zYQUWzWDfdh4TA62H/880Umiq2JduIb3o3DPT+iys5c62iTVw7EctPCDbMEXMEzndvyQ7nWJsb6FJ3aNOA0aRfkUQMwGsG8nReZVD5fdUmZh69Y58v8Z0y5zXMI3UuPr5adn5pH1n09u/qzK8Ooea5ERvfijBV55nQX9K558ANnrOtlMhPCVfthD7YLtYycvNNzgYW3lB+Zv6uokFyGnJjRVMgHiPe75WCQR71T28U6xlJ0GVa+uScaJ23B85/g8et4xX0Na2SwuY6nJeElxadYNUQtjWvJCGLXITAJmql80nvajfhPXNWAvA1ITfO2bJzY3vuooL8U7vo6D0D0bnGUrNoQLIbFpfuTSWzyawVyMoTvIfa9Tl4vtxFUv+ePC+i/QCA7x17UVeFoQ+uTNwcUqwsdDY6sv+LLGA7SZiOYMMgQqE38wY8y1z+pzMbEcF6Bhkti5cB4ki+HLqa0qKSdjb9uiDJfbDX9b4="
  provider: heroku
  strategy: api
  app:
    master: larskj-app1-master
    featureX: larskj-app1-featurex
