sudo: required
language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  api_key:
    secure: "SJ/WRdI7c5MaoztlZ9FNIESIVxhBEnpXm3JjyQ7q4096IC5ttuXpDIWB2yKBMIsIsYP3ddIEG7rNiEyksUcoqgYK4kbwUIpFuaQ3pZN9AOANS5NTx37vTbgduZ1I6/hCVIIPyW7xHFowe0Qz8kxvgv9H/GuTQk6PsRykopOm0XlJXiBQliv5GhxDiBxgDuA+iSeqjJ/NqqYEsbtziub3NMrxRsXq1y+5Wvr/ZWXulGev5pvaVFQvxDW42TT2Mlhyv8IKE26ZkwuM9FFvel90uBxrlpbbvkn2EZOpvkt6eZOpxZ8ihWKR9xLW0xPu2vndOdcfLHfOuRkKRxt3JFHambo6hUHW5EWRBDF/uQ3q85r1nbBnf63VM2KpyP2RtkbroJARZYakoUPoNQ1rgoKKF3ZJqiCuyOX6Aboyqp4io2d+amyCQH8X8KCq7O++fed+oXLUmKw2uJO4IlcKgx2LTkYYJ8dKNer4d9LtcDC48rKrdbBqmZ4IfYd4CCQIAJ3y3YpgDalbCOerSMLsg/wDX+utSuHP6hlNQWerG6XgHNj+2Qdr5qnsg3ggCnNpjyaJSPVguNVBNZFRnwdltoO74hhmwzASyxH6l7I9zuRPn3BkwKlDfbdVsFrMZzldKev8U0WKhr2wKnKA4tXWvYrwdzCXMiIGmrZGBLNUZdrbqok="
  provider: heroku
  strategy: api
  app:
    master: larskj-app1-master
    featureX: larskj-app1-featurex
