sudo: required
language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  api_key:
    secure: PXfL0AXPYU/epJJSS3XudxUhprycLyBf4vId2zJJVx+x/5Ib4dopfPUE0naaImfSYZvGVR6XuHvcp8Mx07CY7phWmT+eSBYEQ1Atp8b12VQc+7oIN9ckMwJAmErVSR2GO1ZJKVtUYENlRg6gdtS2auO2PWXf2fueg4ISINsMiFqN8QK91rLe+g1z6L5OxE9/xQ/TsNC0LBjW9nHu7yRqhwtaVC5N9JoiFpUgVAKo7WmI3kk2Of31v8Laie6zAZyxPSZbhn3wGhp992HdeP8yHLHyKm/qf6DqoT6dDxxQTV3XfePnNBxDdMzQpdY0CvF3fCcbCGYOxjgS17Wzo2VLcF73V9x4crBw+WECARpemcoGOwKxxyeBI2+TK4vBG3J/0OfrwNXNMHtPAHtwut32v777rYKNTqdkOpefdhDbiQI91rWn0E8LrDYlMAh3mVCcLvFgk5e5dTJxzK3mm5Qej7u8uct3wl5O58FrGvzM2WbW203IiQmawS0dEZMUwgollPtipvmSvlQqRFF44M8+Tdp6noqPCqA3KB8howCbu1aqhpsFTcyFnTsMC+rDuD6ANcDHmg5Rpjb+aTsO+z9ED92/Vvv0NrFoeihUN771uXApFBTejrw9xHIdCNqOE6QgQyYI8fAE1qGZlG+52XOOkMKCaelX81XmIGcM4Yw0rGQ=
  provider: heroku
  strategy: api
  app:
    master: larskj-app1-master
    featureX: larskj-app1-featurex
