sudo: required
language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
deploy:
  api_key:
    secure: lUI5y+pxr2Zb82FnOkdaf6niJ+CPziv05XslF6OhG9DSG906k82yDVEvpr67Ag2Mb6kJWtWYOcf0UsdWTDX8T29p2n5DpBNLL5Eiiw/zAoMaw21jngdqamLvYCUBZoeR+iN7eamhd3JW7gEhmNkFZ2dQCbYzp+fbxPpM9fmonCkA7pgg2d7Jw7RJIHCo9OKkxvTB03E6ZATKKzYqf3gBExbobo2qh2sRbDDSTk2wMewhpYrhUmlF+7Fj9b11bt0E90R1TRFk8PQqU+5oVqzCc+Ht0N+23XWAtwiq5oT5jyOSh0X69Gj93rf2chWQj8L0zVbb9ZwZDUlKe716xgXkla8+ufnlc3zpr/voePnV3mStmfe2jMLPTzOTuQmThvFavu/DtdP46urmAgJ7Tvb2wbHXO8ugYbj3gJ4EdLM2VtnbaUd49IW3ICLEgTT8pXDLsdtxxuZykZ+UuWwfB+FTT2TYVcrdoQbUb/LyJ9+sLnXALRmiUghXkPhEnnlJZ3iTebutreSeQOC5Tx3X6yPjk4DysrEEGGWM43xD4fHvPHeaM1aiAXA0HZMtwm2JJnEcU9GVCX5TFLgAWLnRXPKo9+EkImMM/k47LF8NJwYci8Kkkgol1Rtw9ixQc93cP8/NTkFMrqSYPq01D1o6IsAVXBpLTTa26a19pzRGpn7hBWg=
  provider: heroku
  strategy: api
  app:
    master: larskj-app1-master
    featureX: larskj-app1-featurex
